#!/bin/sh

FILE_ELEMENT="filesrc location=$1"
DECODE_BRANCH=" ! decodebin"
CAPS_FILTER=
ENC_ELEMENT=" ! avenc_mpeg2video"
DEC_ELEMENT=" ! avdec_mpeg2video"
SINK_ELEMENT=" ! autovideosink"
BRANCH1="$FILE_ELEMENT $CAPS_FILTER $DECODE_BRANCH $ENC_ELEMENT $DEC_ELEMENT $SINK_ELEMENT"
BRANCH2="$FILE_ELEMENT $CAPS_FILTER $DECODE_BRANCH $ENC_ELEMENT $DEC_ELEMENT $SINK_ELEMENT"

echo $BRANCH1
./gst-n-launch-1.0 -b "$BRANCH1" -b "$BRANCH2"
